<?php

use Illuminate\Database\Seeder;

class MenuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // DISABLE FOREIGN_KEY_CHECKS & TRUNCATE TABLE..
		DB::statement("SET FOREIGN_KEY_CHECKS = 0;");
		DB::statement("TRUNCATE menus;");
		DB::table('menus')->delete();
    	DB::table('menus')->insert(

        [
            array(
                "id" => 1,
                "parent_id" => 0,
                "name" => "Dashboard",
                "url" => "dashboard",
                "icon" => "mdi mdi-view-dashboard",
                "order_number" => 6,
                "is_showed" => 1,
                "method" => "dashboard",
                "created_at" => "2018-08-16 01:26:26",
                "updated_at" => "2019-04-05 10:13:35",
                "deleted_at" => NULL,
            ),
            array(
                "id" => 2,
                "parent_id" => 0,
                "name" => "Pengguna",
                "url" => "user",
                "icon" => "mdi mdi-account",
                "order_number" => 4,
                "is_showed" => 1,
                "method" => "pengguna",
                "created_at" => "2018-08-16 01:28:13",
                "updated_at" => "2018-10-15 16:56:15",
                "deleted_at" => "2018-10-15 16:56:15",
            ),
            array(
                "id" => 3,
                "parent_id" => 0,
                "name" => "Tipe Kendaraan",
                "url" => "type",
                "icon" => "mdi mdi-car",
                "order_number" => 6,
                "is_showed" => 1,
                "method" => "tipe-kendaraan",
                "created_at" => "2018-08-16 01:30:04",
                "updated_at" => "2018-10-14 18:33:53",
                "deleted_at" => "2018-10-14 18:33:53",
            ),
            array(
                "id" => 4,
                "parent_id" => 0,
                "name" => "Grup Lokasi",
                "url" => "group_location",
                "icon" => "mdi mdi-pin",
                "order_number" => 8,
                "is_showed" => 1,
                "method" => "grup-lokasi",
                "created_at" => "2018-08-16 01:30:31",
                "updated_at" => "2018-10-14 18:34:00",
                "deleted_at" => "2018-10-14 18:34:00",
            ),
            array(
                "id" => 5,
                "parent_id" => 0,
                "name" => "Tarif",
                "url" => "rate",
                "icon" => "mdi mdi-currency-usd",
                "order_number" => 10,
                "is_showed" => 1,
                "method" => "tarif",
                "created_at" => "2018-08-16 01:30:56",
                "updated_at" => "2018-10-14 18:34:08",
                "deleted_at" => "2018-10-14 18:34:08",
            ),
            array(
                "id" => 6,
                "parent_id" => 0,
                "name" => "Parkir Histori",
                "url" => "parking_history",
                "icon" => "mdi mdi-parking",
                "order_number" => 12,
                "is_showed" => 1,
                "method" => "parkir-histori",
                "created_at" => "2018-08-16 01:33:32",
                "updated_at" => "2018-10-14 18:34:20",
                "deleted_at" => "2018-10-14 18:34:20",
            ),
            array(
                "id" => 7,
                "parent_id" => 0,
                "name" => "Isi Ulang Histori",
                "url" => "topup_history",
                "icon" => "mdi mdi-book",
                "order_number" => 14,
                "is_showed" => 1,
                "method" => "isi-ulang-histori",
                "created_at" => "2018-08-16 01:34:00",
                "updated_at" => "2018-10-14 18:34:31",
                "deleted_at" => "2018-10-14 18:34:31",
            ),
            array(
                "id" => 8,
                "parent_id" => 14,
                "name" => "Menu",
                "url" => "menu",
                "icon" => NULL,
                "order_number" => 133,
                "is_showed" => 1,
                "method" => "menu",
                "created_at" => "2018-08-16 01:34:18",
                "updated_at" => "2019-08-02 07:49:27",
                "deleted_at" => NULL,
            ),
            array(
                "id" => 14,
                "parent_id" => 0,
                "name" => "Setting",
                "url" => "settings",
                "icon" => "mdi mdi-settings",
                "order_number" => 132,
                "is_showed" => 1,
                "method" => "setting",
                "created_at" => "2018-08-16 01:59:05",
                "updated_at" => "2019-08-02 07:49:26",
                "deleted_at" => NULL,
            ),
            array(
                "id" => 15,
                "parent_id" => 14,
                "name" => "Role",
                "url" => "settings/role",
                "icon" => NULL,
                "order_number" => 141,
                "is_showed" => 1,
                "method" => "role",
                "created_at" => "2018-08-16 01:59:36",
                "updated_at" => "2019-08-02 07:49:27",
                "deleted_at" => NULL,
            ),
            array(
                "id" => 16,
                "parent_id" => 14,
                "name" => "User Role",
                "url" => "settings/permission",
                "icon" => NULL,
                "order_number" => 143,
                "is_showed" => 1,
                "method" => "user-role",
                "created_at" => "2018-08-16 01:59:59",
                "updated_at" => "2019-08-02 07:49:27",
                "deleted_at" => NULL,
            ),
            array(
                "id" => 17,
                "parent_id" => 0,
                "name" => "FAQ",
                "url" => "faq",
                "icon" => "mdi mdi-help-circle",
                "order_number" => 32,
                "is_showed" => 1,
                "method" => "faq",
                "created_at" => "2018-08-22 23:41:18",
                "updated_at" => "2018-10-15 16:55:46",
                "deleted_at" => "2018-10-15 16:55:46",
            ),
            array(
                "id" => 18,
                "parent_id" => 0,
                "name" => "Bantuan",
                "url" => "help",
                "icon" => "mdi mdi-help-circle-outline",
                "order_number" => 34,
                "is_showed" => 1,
                "method" => "bantuan",
                "created_at" => "2018-08-22 23:41:42",
                "updated_at" => "2018-10-15 16:55:50",
                "deleted_at" => "2018-10-15 16:55:50",
            ),
            array(
                "id" => 24,
                "parent_id" => 0,
                "name" => "Upload Data",
                "url" => "upload",
                "icon" => "glyphicon glyphicon-upload",
                "order_number" => 16,
                "is_showed" => 1,
                "method" => "upload-data",
                "created_at" => "2018-10-14 18:36:12",
                "updated_at" => "2019-04-05 10:30:59",
                "deleted_at" => NULL,
            ),
            array(
                "id" => 25,
                "parent_id" => 24,
                "name" => "Upload BOM Finish Goods",
                "url" => "bom",
                "icon" => "glyphicon glyphicon-upload",
                "order_number" => 19,
                "is_showed" => 1,
                "method" => "upload-bom-finish-goods",
                "created_at" => "2018-10-14 18:36:56",
                "updated_at" => "2019-08-01 14:16:29",
                "deleted_at" => NULL,
            ),
            array(
                "id" => 26,
                "parent_id" => 24,
                "name" => "Upload Master Price Part",
                "url" => "masterprice",
                "icon" => "glyphicon glyphicon-upload",
                "order_number" => 23,
                "is_showed" => 1,
                "method" => "upload-master-price-parts",
                "created_at" => "2018-10-14 18:38:20",
                "updated_at" => "2019-08-01 14:19:16",
                "deleted_at" => NULL,
            ),
            array(
                "id" => 27,
                "parent_id" => 24,
                "name" => "Upload Sales Data",
                "url" => "salesdata",
                "icon" => "glyphicon glyphicon-upload",
                "order_number" => 17,
                "is_showed" => 1,
                "method" => "upload-sales-data",
                "created_at" => "2018-10-14 18:39:17",
                "updated_at" => "2019-04-16 16:09:05",
                "deleted_at" => NULL,
            ),
            array(
                "id" => 28,
                "parent_id" => 0,
                "name" => "Master Data",
                "url" => "master",
                "icon" => "mdi mdi-book",
                "order_number" => 28,
                "is_showed" => 1,
                "method" => "master-data",
                "created_at" => "2018-10-15 16:49:33",
                "updated_at" => "2019-04-05 10:30:59",
                "deleted_at" => NULL,
            ),
            array(
                "id" => 29,
                "parent_id" => 28,
                "name" => "Division",
                "url" => "division",
                "icon" => NULL,
                "order_number" => 29,
                "is_showed" => 1,
                "method" => "master-data",
                "created_at" => "2018-10-15 16:51:25",
                "updated_at" => "2019-04-05 10:30:59",
                "deleted_at" => NULL,
            ),
            array(
                "id" => 30,
                "parent_id" => 28,
                "name" => "Department",
                "url" => "department",
                "icon" => NULL,
                "order_number" => 31,
                "is_showed" => 1,
                "method" => "department",
                "created_at" => "2018-10-15 16:51:47",
                "updated_at" => "2019-04-25 08:23:23",
                "deleted_at" => NULL,
            ),
            array(
                "id" => 31,
                "parent_id" => 28,
                "name" => "Employee",
                "url" => "employee",
                "icon" => "mdi mdi-account",
                "order_number" => 17,
                "is_showed" => 1,
                "method" => "dashboard",
                "created_at" => "2018-10-15 16:52:30",
                "updated_at" => "2018-10-18 11:24:25",
                "deleted_at" => "2018-10-18 11:24:25",
            ),
            array(
                "id" => 32,
                "parent_id" => 28,
                "name" => "Customer",
                "url" => "customer",
                "icon" => NULL,
                "order_number" => 35,
                "is_showed" => 1,
                "method" => "master-data",
                "created_at" => "2018-10-15 16:53:22",
                "updated_at" => "2019-08-02 07:37:01",
                "deleted_at" => NULL,
            ),
            array(
                "id" => 33,
                "parent_id" => 28,
                "name" => "Supplier",
                "url" => "supplier",
                "icon" => NULL,
                "order_number" => 37,
                "is_showed" => 1,
                "method" => "master-data",
                "created_at" => "2018-10-15 16:53:37",
                "updated_at" => "2019-08-02 07:37:01",
                "deleted_at" => NULL,
            ),
            array(
                "id" => 34,
                "parent_id" => 28,
                "name" => "Plant",
                "url" => "plant",
                "icon" => NULL,
                "order_number" => 23,
                "is_showed" => 1,
                "method" => "dashboard",
                "created_at" => "2018-10-15 16:54:19",
                "updated_at" => "2018-10-17 15:45:25",
                "deleted_at" => "2018-10-17 15:45:25",
            ),
            array(
                "id" => 35,
                "parent_id" => 28,
                "name" => "Part Category",
                "url" => "category_part",
                "icon" => NULL,
                "order_number" => 25,
                "is_showed" => 1,
                "method" => "dashboard",
                "created_at" => "2018-10-15 16:54:44",
                "updated_at" => "2018-10-17 15:37:44",
                "deleted_at" => "2018-10-17 15:37:44",
            ),
            array(
                "id" => 36,
                "parent_id" => 28,
                "name" => "Part",
                "url" => "part",
                "icon" => NULL,
                "order_number" => 39,
                "is_showed" => 1,
                "method" => "part",
                "created_at" => "2018-10-15 16:55:09",
                "updated_at" => "2019-08-02 07:37:01",
                "deleted_at" => NULL,
            ),
            array(
                "id" => 37,
                "parent_id" => 14,
                "name" => "System",
                "url" => "system",
                "icon" => NULL,
                "order_number" => 135,
                "is_showed" => 1,
                "method" => "setting",
                "created_at" => "2018-10-16 15:21:44",
                "updated_at" => "2019-08-02 07:49:27",
                "deleted_at" => NULL,
            ),
            array(
                "id" => 38,
                "parent_id" => 28,
                "name" => "Catalog",
                "url" => "catalog",
                "icon" => NULL,
                "order_number" => 41,
                "is_showed" => 1,
                "method" => "data-catalog",
                "created_at" => "2018-10-17 15:38:09",
                "updated_at" => "2019-08-02 07:37:01",
                "deleted_at" => NULL,
            ),
            array(
                "id" => 39,
                "parent_id" => 14,
                "name" => "User",
                "url" => "user",
                "icon" => NULL,
                "order_number" => 137,
                "is_showed" => 1,
                "method" => "users",
                "created_at" => "2018-10-18 11:25:00",
                "updated_at" => "2019-08-02 07:49:27",
                "deleted_at" => NULL,
            ),
            array(
                "id" => 40,
                "parent_id" => 24,
                "name" => "Upload Budget",
                "url" => "budgetplanning",
                "icon" => "glyphicon glyphicon-upload",
                "order_number" => 9,
                "is_showed" => 1,
                "method" => "approval-create",
                "created_at" => "2018-10-18 18:38:09",
                "updated_at" => "2019-01-07 05:08:52",
                "deleted_at" => "2019-01-07 05:08:52",
            ),
            array(
                "id" => 41,
                "parent_id" => 24,
                "name" => "Upload Master Price Catalog",
                "url" => "price_catalogue",
                "icon" => "glyphicon glyphicon-upload",
                "order_number" => 19,
                "is_showed" => 1,
                "method" => "budget_upload",
                "created_at" => "2018-10-18 19:22:25",
                "updated_at" => "2019-01-24 05:24:55",
                "deleted_at" => "2019-01-24 05:24:55",
            ),
            array(
                "id" => 42,
                "parent_id" => 24,
                "name" => "Upload BOM Semi Finish Goods",
                "url" => "bom_semi",
                "icon" => "glyphicon glyphicon-upload",
                "order_number" => 21,
                "is_showed" => 1,
                "method" => "upload-bom-semi-finish-goods",
                "created_at" => "2018-10-18 19:23:39",
                "updated_at" => "2019-08-01 14:16:14",
                "deleted_at" => NULL,
            ),
            array(
                "id" => 43,
                "parent_id" => 24,
                "name" => "Output Master",
                "url" => "output_master",
                "icon" => "glyphicon glyphicon-upload",
                "order_number" => 25,
                "is_showed" => 1,
                "method" => "output-master",
                "created_at" => "2018-11-05 19:18:51",
                "updated_at" => "2019-08-01 14:22:17",
                "deleted_at" => NULL,
            ),
            array(
                "id" => 44,
                "parent_id" => 0,
                "name" => "Capex",
                "url" => "capex",
                "icon" => "fa fa-bank",
                "order_number" => 76,
                "is_showed" => 1,
                "method" => "capex",
                "created_at" => "2018-11-12 21:51:59",
                "updated_at" => "2019-08-02 07:53:43",
                "deleted_at" => NULL,
            ),
            array(
                "id" => 45,
                "parent_id" => 44,
                "name" => "List",
                "url" => "capex",
                "icon" => NULL,
                "order_number" => 77,
                "is_showed" => 1,
                "method" => "list-capex",
                "created_at" => "2018-11-13 21:22:35",
                "updated_at" => "2019-08-02 07:53:43",
                "deleted_at" => NULL,
            ),
            array(
                "id" => 46,
                "parent_id" => 44,
                "name" => "List Approval",
                "url" => "approval/cx",
                "icon" => NULL,
                "order_number" => 81,
                "is_showed" => 1,
                "method" => "list-approval-capex",
                "created_at" => "2018-11-13 21:35:56",
                "updated_at" => "2019-08-02 07:53:43",
                "deleted_at" => NULL,
            ),
            array(
                "id" => 47,
                "parent_id" => 44,
                "name" => "Create Approval",
                "url" => "approval/create/cx",
                "icon" => NULL,
                "order_number" => 83,
                "is_showed" => 1,
                "method" => "create-approval-capex",
                "created_at" => "2018-11-13 21:49:10",
                "updated_at" => "2019-08-02 07:53:43",
                "deleted_at" => NULL,
            ),
            array(
                "id" => 48,
                "parent_id" => 0,
                "name" => "Create Approval",
                "url" => "approval/cx/create",
                "icon" => NULL,
                "order_number" => 27,
                "is_showed" => 1,
                "method" => "dashboard",
                "created_at" => "2018-11-14 18:35:37",
                "updated_at" => "2018-11-14 18:35:54",
                "deleted_at" => "2018-11-14 18:35:54",
            ),
            array(
                "id" => 49,
                "parent_id" => 44,
                "name" => "Cip Settlement",
                "url" => "cip/settlement/list",
                "icon" => NULL,
                "order_number" => 87,
                "is_showed" => 1,
                "method" => "cip-sattlement",
                "created_at" => "2018-11-14 18:49:09",
                "updated_at" => "2019-08-02 07:53:43",
                "deleted_at" => NULL,
            ),
            array(
                "id" => 50,
                "parent_id" => 0,
                "name" => "Expense",
                "url" => "expense",
                "icon" => "fa fa-bank",
                "order_number" => 92,
                "is_showed" => 1,
                "method" => "expense",
                "created_at" => "2018-11-14 18:50:08",
                "updated_at" => "2019-08-02 07:53:43",
                "deleted_at" => NULL,
            ),
            array(
                "id" => 51,
                "parent_id" => 50,
                "name" => "List",
                "url" => "expense",
                "icon" => NULL,
                "order_number" => 93,
                "is_showed" => 1,
                "method" => "list-expense",
                "created_at" => "2018-11-14 18:50:55",
                "updated_at" => "2019-08-02 07:53:43",
                "deleted_at" => NULL,
            ),
            array(
                "id" => 52,
                "parent_id" => 50,
                "name" => "List Approval",
                "url" => "approval/ex",
                "icon" => NULL,
                "order_number" => 99,
                "is_showed" => 1,
                "method" => "list-approval-expense",
                "created_at" => "2018-11-14 18:51:31",
                "updated_at" => "2019-08-02 07:53:43",
                "deleted_at" => NULL,
            ),
            array(
                "id" => 53,
                "parent_id" => 50,
                "name" => "Create Approval",
                "url" => "approval/create/ex",
                "icon" => NULL,
                "order_number" => 97,
                "is_showed" => 1,
                "method" => "create-approval-expense",
                "created_at" => "2018-11-14 18:52:00",
                "updated_at" => "2019-08-02 07:53:43",
                "deleted_at" => NULL,
            ),
            array(
                "id" => 54,
                "parent_id" => 0,
                "name" => "Unbudget",
                "url" => "unbuget",
                "icon" => "fa fa-bank",
                "order_number" => 102,
                "is_showed" => 1,
                "method" => "unbudget",
                "created_at" => "2018-11-14 18:52:47",
                "updated_at" => "2019-08-02 07:53:43",
                "deleted_at" => NULL,
            ),
            array(
                "id" => 55,
                "parent_id" => 54,
                "name" => "List Approval",
                "url" => "approval/ub",
                "icon" => NULL,
                "order_number" => 103,
                "is_showed" => 1,
                "method" => "list-approval-unbudget",
                "created_at" => "2018-11-14 18:53:43",
                "updated_at" => "2019-08-02 07:53:43",
                "deleted_at" => NULL,
            ),
            array(
                "id" => 56,
                "parent_id" => 54,
                "name" => "Create Approval",
                "url" => "approval/create/ub",
                "icon" => NULL,
                "order_number" => 105,
                "is_showed" => 1,
                "method" => "create-approval-unbudget",
                "created_at" => "2018-11-14 18:54:16",
                "updated_at" => "2019-08-02 07:53:43",
                "deleted_at" => NULL,
            ),
            array(
                "id" => 57,
                "parent_id" => 44,
                "name" => "CIP Administrator",
                "url" => "cip/admin/list",
                "icon" => NULL,
                "order_number" => 85,
                "is_showed" => 1,
                "method" => "cip-admin-list",
                "created_at" => "2018-11-21 19:37:27",
                "updated_at" => "2019-08-02 07:53:43",
                "deleted_at" => NULL,
            ),
            array(
                "id" => 58,
                "parent_id" => 50,
                "name" => "Pending Approval",
                "url" => "approval/ex/unvalidated",
                "icon" => NULL,
                "order_number" => 95,
                "is_showed" => 1,
                "method" => "list-approval-expense",
                "created_at" => "2018-11-22 21:15:07",
                "updated_at" => "2019-08-02 07:53:43",
                "deleted_at" => NULL,
            ),
            array(
                "id" => 59,
                "parent_id" => 0,
                "name" => "Closing",
                "url" => "Closing",
                "icon" => "fa fa-lock",
                "order_number" => 110,
                "is_showed" => 1,
                "method" => "fyear_closing",
                "created_at" => "2018-11-22 21:20:29",
                "updated_at" => "2019-08-02 07:53:43",
                "deleted_at" => NULL,
            ),
            array(
                "id" => 60,
                "parent_id" => 59,
                "name" => "Capex",
                "url" => "capex/closing",
                "icon" => NULL,
                "order_number" => 111,
                "is_showed" => 1,
                "method" => "closing-expense",
                "created_at" => "2018-11-22 21:21:26",
                "updated_at" => "2019-08-02 07:53:43",
                "deleted_at" => NULL,
            ),
            array(
                "id" => 61,
                "parent_id" => 59,
                "name" => "Expense",
                "url" => "expense/closing",
                "icon" => NULL,
                "order_number" => 113,
                "is_showed" => 1,
                "method" => "closing-expense",
                "created_at" => "2018-11-22 21:22:07",
                "updated_at" => "2019-08-02 07:53:43",
                "deleted_at" => NULL,
            ),
            array(
                "id" => 62,
                "parent_id" => 0,
                "name" => "Archive",
                "url" => "archive",
                "icon" => "fa fa-file-archive-o",
                "order_number" => 116,
                "is_showed" => 1,
                "method" => "archive",
                "created_at" => "2018-11-22 21:23:44",
                "updated_at" => "2019-08-02 07:53:43",
                "deleted_at" => NULL,
            ),
            array(
                "id" => 63,
                "parent_id" => 62,
                "name" => "Capex",
                "url" => "capex/archive",
                "icon" => NULL,
                "order_number" => 117,
                "is_showed" => 1,
                "method" => "archive-capex",
                "created_at" => "2018-11-22 21:24:31",
                "updated_at" => "2019-08-02 07:53:43",
                "deleted_at" => NULL,
            ),
            array(
                "id" => 64,
                "parent_id" => 62,
                "name" => "Expense",
                "url" => "expense/archive",
                "icon" => NULL,
                "order_number" => 119,
                "is_showed" => 1,
                "method" => "archive-expense",
                "created_at" => "2018-11-22 21:24:49",
                "updated_at" => "2019-08-02 08:17:27",
                "deleted_at" => NULL,
            ),
            array(
                "id" => 65,
                "parent_id" => 0,
                "name" => "Upload",
                "url" => "upload",
                "icon" => "fa fa-upload",
                "order_number" => 122,
                "is_showed" => 1,
                "method" => "upload",
                "created_at" => "2018-11-22 21:25:26",
                "updated_at" => "2019-08-02 07:53:43",
                "deleted_at" => NULL,
            ),
            array(
                "id" => 66,
                "parent_id" => 65,
                "name" => "Capex Upload",
                "url" => "capex/upload",
                "icon" => NULL,
                "order_number" => 123,
                "is_showed" => 1,
                "method" => "upload-capex",
                "created_at" => "2018-11-22 21:25:52",
                "updated_at" => "2019-08-02 07:53:43",
                "deleted_at" => NULL,
            ),
            array(
                "id" => 67,
                "parent_id" => 65,
                "name" => "Expense Upload",
                "url" => "expense/upload",
                "icon" => NULL,
                "order_number" => 125,
                "is_showed" => 1,
                "method" => "upload-expense",
                "created_at" => "2018-11-22 21:26:19",
                "updated_at" => "2019-08-02 07:53:43",
                "deleted_at" => NULL,
            ),
            array(
                "id" => 68,
                "parent_id" => 70,
                "name" => "SAP Asset",
                "url" => "asset",
                "icon" => NULL,
                "order_number" => 49,
                "is_showed" => 1,
                "method" => "sap-asset",
                "created_at" => "2018-11-28 18:38:30",
                "updated_at" => "2019-08-02 07:37:01",
                "deleted_at" => NULL,
            ),
            array(
                "id" => 69,
                "parent_id" => 70,
                "name" => "SAP Cost Center",
                "url" => "cost_center",
                "icon" => NULL,
                "order_number" => 51,
                "is_showed" => 1,
                "method" => "sap-cost-center",
                "created_at" => "2018-11-28 18:39:57",
                "updated_at" => "2019-08-02 07:37:01",
                "deleted_at" => NULL,
            ),
            array(
                "id" => 70,
                "parent_id" => 0,
                "name" => "Master SAP",
                "url" => "sap",
                "icon" => "mdi mdi-book",
                "order_number" => 48,
                "is_showed" => 1,
                "method" => "master-sap",
                "created_at" => "2018-11-28 18:40:26",
                "updated_at" => "2019-08-02 07:37:01",
                "deleted_at" => NULL,
            ),
            array(
                "id" => 71,
                "parent_id" => 70,
                "name" => "SAP Gl Account",
                "url" => "gl_account",
                "icon" => NULL,
                "order_number" => 53,
                "is_showed" => 1,
                "method" => "sap-gl-account",
                "created_at" => "2018-11-28 18:42:01",
                "updated_at" => "2019-08-02 07:37:01",
                "deleted_at" => NULL,
            ),
            array(
                "id" => 72,
                "parent_id" => 70,
                "name" => "SAP Number",
                "url" => "number",
                "icon" => NULL,
                "order_number" => 55,
                "is_showed" => 1,
                "method" => "sap-number",
                "created_at" => "2018-11-28 18:43:13",
                "updated_at" => "2019-08-02 07:37:01",
                "deleted_at" => NULL,
            ),
            array(
                "id" => 73,
                "parent_id" => 70,
                "name" => "SAP Taxes",
                "url" => "taxe",
                "icon" => NULL,
                "order_number" => 57,
                "is_showed" => 1,
                "method" => "sap-taxes",
                "created_at" => "2018-11-28 18:43:35",
                "updated_at" => "2019-08-02 07:37:01",
                "deleted_at" => NULL,
            ),
            array(
                "id" => 74,
                "parent_id" => 70,
                "name" => "SAP Uom",
                "url" => "uom",
                "icon" => NULL,
                "order_number" => 59,
                "is_showed" => 1,
                "method" => "sap-uom",
                "created_at" => "2018-11-28 18:44:01",
                "updated_at" => "2019-08-02 07:37:01",
                "deleted_at" => NULL,
            ),
            array(
                "id" => 75,
                "parent_id" => 70,
                "name" => "SAP Vendor",
                "url" => "vendor",
                "icon" => NULL,
                "order_number" => 61,
                "is_showed" => 1,
                "method" => "sap-vendor",
                "created_at" => "2018-11-28 18:44:22",
                "updated_at" => "2019-08-02 07:37:01",
                "deleted_at" => NULL,
            ),
            array(
                "id" => 76,
                "parent_id" => 28,
                "name" => "Approval",
                "url" => "manage_approval",
                "icon" => NULL,
                "order_number" => 45,
                "is_showed" => 1,
                "method" => "approval",
                "created_at" => "2018-12-05 19:58:23",
                "updated_at" => "2019-08-02 07:37:01",
                "deleted_at" => NULL,
            ),
            array(
                "id" => 77,
                "parent_id" => 14,
                "name" => "Manage User",
                "url" => "user",
                "icon" => NULL,
                "order_number" => 139,
                "is_showed" => 1,
                "method" => "manage-user",
                "created_at" => "2018-12-06 01:37:08",
                "updated_at" => "2019-08-02 07:49:27",
                "deleted_at" => NULL,
            ),
            array(
                "id" => 78,
                "parent_id" => 0,
                "name" => "Manage User",
                "url" => "manage_user",
                "icon" => NULL,
                "order_number" => 56,
                "is_showed" => 1,
                "method" => NULL,
                "created_at" => "2018-12-06 20:13:08",
                "updated_at" => "2018-12-06 20:27:02",
                "deleted_at" => "2018-12-06 20:27:02",
            ),
            array(
                "id" => 79,
                "parent_id" => 28,
                "name" => "Period",
                "url" => "period",
                "icon" => NULL,
                "order_number" => 43,
                "is_showed" => 1,
                "method" => "periode",
                "created_at" => "2018-12-17 20:38:49",
                "updated_at" => "2019-08-02 07:37:01",
                "deleted_at" => NULL,
            ),
            array(
                "id" => 80,
                "parent_id" => 0,
                "name" => "Home",
                "url" => "home",
                "icon" => "mdi mdi-home-variant",
                "order_number" => 2,
                "is_showed" => 1,
                "method" => "approval-create",
                "created_at" => "2019-01-06 20:12:19",
                "updated_at" => "2019-01-06 20:16:18",
                "deleted_at" => NULL,
            ),
            array(
                "id" => 81,
                "parent_id" => 80,
                "name" => "Bussines FLow",
                "url" => "home",
                "icon" => NULL,
                "order_number" => 3,
                "is_showed" => 1,
                "method" => "approval-create",
                "created_at" => "2019-01-06 20:17:10",
                "updated_at" => "2019-01-06 20:17:39",
                "deleted_at" => NULL,
            ),
            array(
                "id" => 82,
                "parent_id" => 84,
                "name" => "Item Category",
                "url" => "item_category",
                "icon" => NULL,
                "order_number" => 65,
                "is_showed" => 1,
                "method" => "item-category",
                "created_at" => "2019-01-16 07:20:17",
                "updated_at" => "2019-08-02 07:37:01",
                "deleted_at" => NULL,
            ),
            array(
                "id" => 83,
                "parent_id" => 84,
                "name" => "Item",
                "url" => "item",
                "icon" => NULL,
                "order_number" => 67,
                "is_showed" => 1,
                "method" => "item",
                "created_at" => "2019-01-16 07:20:47",
                "updated_at" => "2019-08-02 07:37:01",
                "deleted_at" => NULL,
            ),
            array(
                "id" => 84,
                "parent_id" => 0,
                "name" => "EPS",
                "url" => "eps",
                "icon" => "fa fa-shopping-cart",
                "order_number" => 64,
                "is_showed" => 1,
                "method" => "eps",
                "created_at" => "2019-02-04 02:34:33",
                "updated_at" => "2019-08-02 07:37:01",
                "deleted_at" => NULL,
            ),
            array(
                "id" => 85,
                "parent_id" => 84,
                "name" => "Upload PO",
                "url" => "upload_po",
                "icon" => NULL,
                "order_number" => 69,
                "is_showed" => 1,
                "method" => "upload-po",
                "created_at" => "2019-02-04 02:38:26",
                "updated_at" => "2019-08-02 07:37:01",
                "deleted_at" => NULL,
            ),
            array(
                "id" => 86,
                "parent_id" => 84,
                "name" => "GR Confirmation",
                "url" => "gr_confirm",
                "icon" => NULL,
                "order_number" => 71,
                "is_showed" => 1,
                "method" => "gr-confirm",
                "created_at" => "2019-02-04 02:38:52",
                "updated_at" => "2019-08-02 07:37:01",
                "deleted_at" => NULL,
            ),
            array(
                "id" => 87,
                "parent_id" => 84,
                "name" => "EPS Tracking",
                "url" => "eps_tracking",
                "icon" => NULL,
                "order_number" => 73,
                "is_showed" => 1,
                "method" => "eps-tracking",
                "created_at" => "2019-02-04 02:39:08",
                "updated_at" => "2019-08-02 07:37:01",
                "deleted_at" => NULL,
            ),
            array(
                "id" => 88,
                "parent_id" => 44,
                "name" => "Pending Approval",
                "url" => "approval/cx/unvalidated",
                "icon" => NULL,
                "order_number" => 79,
                "is_showed" => 1,
                "method" => "pending-approval-capex",
                "created_at" => "2019-03-25 16:00:45",
                "updated_at" => "2019-08-02 07:53:43",
                "deleted_at" => NULL,
            ),
            array(
                "id" => 90,
                "parent_id" => 44,
                "name" => "Pending Asset Assign No",
                "url" => "cip/settlement/list",
                "icon" => NULL,
                "order_number" => 89,
                "is_showed" => 1,
                "method" => "pending-asset-assign-no-capex",
                "created_at" => "2019-03-25 16:13:13",
                "updated_at" => "2019-08-02 07:53:43",
                "deleted_at" => NULL,
            ),
            array(
                "id" => 91,
                "parent_id" => 54,
                "name" => "Pending Approval",
                "url" => "approval/ub",
                "icon" => NULL,
                "order_number" => 107,
                "is_showed" => 1,
                "method" => "pending-approval-expense",
                "created_at" => "2019-03-25 16:16:27",
                "updated_at" => "2019-08-02 07:53:43",
                "deleted_at" => NULL,
            ),
            array(
                "id" => 92,
                "parent_id" => 1,
                "name" => "All Divisions",
                "url" => "dashboard/view/all",
                "icon" => NULL,
                "order_number" => 7,
                "is_showed" => 1,
                "method" => "all-divisions",
                "created_at" => "2019-04-05 10:28:46",
                "updated_at" => "2019-04-05 10:31:08",
                "deleted_at" => NULL,
            ),
            array(
                "id" => 93,
                "parent_id" => 1,
                "name" => "Adm Divisions",
                "url" => "dashboard/view/Administration",
                "icon" => NULL,
                "order_number" => 13,
                "is_showed" => 1,
                "method" => "adm-divisions",
                "created_at" => "2019-04-05 10:29:14",
                "updated_at" => "2019-04-05 10:32:36",
                "deleted_at" => NULL,
            ),
            array(
                "id" => 94,
                "parent_id" => 1,
                "name" => "Eng Divisions",
                "url" => "dashboard/view/Engineering",
                "icon" => NULL,
                "order_number" => 11,
                "is_showed" => 1,
                "method" => "eng-divisions",
                "created_at" => "2019-04-05 10:29:28",
                "updated_at" => "2019-04-05 10:32:48",
                "deleted_at" => NULL,
            ),
            array(
                "id" => 95,
                "parent_id" => 1,
                "name" => "Prd Divisions",
                "url" => "dashboard/view/Production",
                "icon" => NULL,
                "order_number" => 9,
                "is_showed" => 1,
                "method" => "prd-divisions",
                "created_at" => "2019-04-05 10:29:47",
                "updated_at" => "2019-04-05 10:33:04",
                "deleted_at" => NULL,
            ),
            array(
                "id" => 96,
                "parent_id" => 28,
                "name" => "Section",
                "url" => "section",
                "icon" => NULL,
                "order_number" => 33,
                "is_showed" => 1,
                "method" => "section",
                "created_at" => "2019-08-02 07:36:39",
                "updated_at" => "2019-08-02 07:37:01",
                "deleted_at" => NULL,
            ),
            array(
                "id" => 97,
                "parent_id" => 98,
                "name" => "Link To SAP",
                "url" => "link_to_sap",
                "icon" => NULL,
                "order_number" => 129,
                "is_showed" => 1,
                "method" => "link-to-sap",
                "created_at" => "2019-08-02 07:48:19",
                "updated_at" => "2019-08-02 07:53:43",
                "deleted_at" => NULL,
            ),
            array(
                "id" => 98,
                "parent_id" => 0,
                "name" => "Download SAP",
                "url" => "link-to-sap",
                "icon" => "fa fa-download",
                "order_number" => 128,
                "is_showed" => 1,
                "method" => "link-to-sap",
                "created_at" => "2019-08-02 07:49:14",
                "updated_at" => "2019-08-02 07:53:43",
                "deleted_at" => NULL,
            ),
        ]);
        
            // Activate FOREIGN_KEY_CHECKS again..
            DB::statement("SET FOREIGN_KEY_CHECKS = 1;");
        
    }
}
