<?php

use Illuminate\Database\Seeder;
use App\Permission;

class PermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // DISABLE FOREIGN_KEY_CHECKS & TRUNCATE TABLE..
		DB::statement("SET FOREIGN_KEY_CHECKS = 0;");
		DB::statement("TRUNCATE permissions;");
		DB::table('permissions')->delete();
    	DB::table('permissions')->insert(

		[
            array(
                "id" => 1,
                "parent_id" => 0,
                "name" => "setting",
                "display_name" => "Setting",
                "description" => NULL,
                "created_at" => "2019-04-02 14:23:01",
                "updated_at" => "2019-04-02 14:23:01",
            ),
            array(
                "id" => 2,
                "parent_id" => 1,
                "name" => "menu",
                "display_name" => "Menu",
                "description" => NULL,
                "created_at" => "2019-04-02 14:23:12",
                "updated_at" => "2019-04-02 14:23:12",
            ),
            array(
                "id" => 3,
                "parent_id" => 1,
                "name" => "system",
                "display_name" => "System",
                "description" => NULL,
                "created_at" => "2019-04-02 14:23:28",
                "updated_at" => "2019-04-02 14:23:28",
            ),
            array(
                "id" => 4,
                "parent_id" => 1,
                "name" => "users",
                "display_name" => "Users",
                "description" => NULL,
                "created_at" => "2019-04-02 14:23:46",
                "updated_at" => "2019-04-02 14:23:46",
            ),
            array(
                "id" => 5,
                "parent_id" => 1,
                "name" => "role",
                "display_name" => "Roles",
                "description" => NULL,
                "created_at" => "2019-04-02 14:23:57",
                "updated_at" => "2019-04-02 14:23:57",
            ),
            array(
                "id" => 6,
                "parent_id" => 1,
                "name" => "user-role",
                "display_name" => "User Role",
                "description" => NULL,
                "created_at" => "2019-04-02 14:24:15",
                "updated_at" => "2019-04-02 14:24:15",
            ),
            array(
                "id" => 7,
                "parent_id" => 0,
                "name" => "capex",
                "display_name" => "Capex",
                "description" => NULL,
                "created_at" => "2019-04-02 14:36:20",
                "updated_at" => "2019-04-02 14:36:20",
            ),
            array(
                "id" => 8,
                "parent_id" => 7,
                "name" => "list-capex",
                "display_name" => "List Capex",
                "description" => NULL,
                "created_at" => "2019-04-02 14:37:09",
                "updated_at" => "2019-04-02 14:37:09",
            ),
            array(
                "id" => 9,
                "parent_id" => 7,
                "name" => "list-approval-capex",
                "display_name" => "List Approval Capex",
                "description" => NULL,
                "created_at" => "2019-04-02 14:37:33",
                "updated_at" => "2019-04-02 14:37:33",
            ),
            array(
                "id" => 10,
                "parent_id" => 7,
                "name" => "create-approval-capex",
                "display_name" => "Create Approval Capex",
                "description" => NULL,
                "created_at" => "2019-04-02 14:37:57",
                "updated_at" => "2019-04-02 14:37:57",
            ),
            array(
                "id" => 11,
                "parent_id" => 7,
                "name" => "cip-admin-list",
                "display_name" => "CIP Admin List",
                "description" => NULL,
                "created_at" => "2019-04-02 14:38:18",
                "updated_at" => "2019-04-25 09:03:27",
            ),
            array(
                "id" => 12,
                "parent_id" => 7,
                "name" => "cip-sattlement",
                "display_name" => "CIP Sattlement",
                "description" => NULL,
                "created_at" => "2019-04-02 14:38:53",
                "updated_at" => "2019-04-02 14:38:53",
            ),
            array(
                "id" => 13,
                "parent_id" => 7,
                "name" => "pending-approval-capex",
                "display_name" => "Pending Approval Capex",
                "description" => NULL,
                "created_at" => "2019-04-02 14:42:29",
                "updated_at" => "2019-04-02 14:42:29",
            ),
            array(
                "id" => 14,
                "parent_id" => 0,
                "name" => "expense",
                "display_name" => "Expense",
                "description" => NULL,
                "created_at" => "2019-04-05 08:41:46",
                "updated_at" => "2019-04-05 08:41:46",
            ),
            array(
                "id" => 15,
                "parent_id" => 14,
                "name" => "list-expense",
                "display_name" => "List Expense",
                "description" => NULL,
                "created_at" => "2019-04-05 08:42:21",
                "updated_at" => "2019-04-05 08:42:21",
            ),
            array(
                "id" => 16,
                "parent_id" => 14,
                "name" => "pending-approval-expense",
                "display_name" => "Pending Approval Expense",
                "description" => NULL,
                "created_at" => "2019-04-05 08:42:43",
                "updated_at" => "2019-04-05 08:42:43",
            ),
            array(
                "id" => 17,
                "parent_id" => 14,
                "name" => "list-approval-expense",
                "display_name" => "List Approval Expense",
                "description" => NULL,
                "created_at" => "2019-04-05 08:43:03",
                "updated_at" => "2019-04-05 08:43:03",
            ),
            array(
                "id" => 18,
                "parent_id" => 14,
                "name" => "create-approval-expense",
                "display_name" => "Create Approval Expense",
                "description" => NULL,
                "created_at" => "2019-04-05 08:43:24",
                "updated_at" => "2019-04-05 08:43:24",
            ),
            array(
                "id" => 19,
                "parent_id" => 0,
                "name" => "master-data",
                "display_name" => "Master Data",
                "description" => NULL,
                "created_at" => "2019-04-05 08:46:28",
                "updated_at" => "2019-04-05 08:46:28",
            ),
            array(
                "id" => 20,
                "parent_id" => 19,
                "name" => "division",
                "display_name" => "Division",
                "description" => NULL,
                "created_at" => "2019-04-05 08:50:23",
                "updated_at" => "2019-04-25 08:24:09",
            ),
            array(
                "id" => 21,
                "parent_id" => 19,
                "name" => "department",
                "display_name" => "Department",
                "description" => NULL,
                "created_at" => "2019-04-05 08:50:49",
                "updated_at" => "2019-04-25 08:23:08",
            ),
            array(
                "id" => 22,
                "parent_id" => 19,
                "name" => "customer",
                "display_name" => "Customer",
                "description" => NULL,
                "created_at" => "2019-04-05 08:51:32",
                "updated_at" => "2019-04-16 14:04:23",
            ),
            array(
                "id" => 23,
                "parent_id" => 19,
                "name" => "supplier",
                "display_name" => "Supplier",
                "description" => NULL,
                "created_at" => "2019-04-05 08:51:50",
                "updated_at" => "2019-04-25 08:24:38",
            ),
            array(
                "id" => 24,
                "parent_id" => 19,
                "name" => "part",
                "display_name" => "Part",
                "description" => NULL,
                "created_at" => "2019-04-05 08:52:08",
                "updated_at" => "2019-04-25 08:29:10",
            ),
            array(
                "id" => 25,
                "parent_id" => 19,
                "name" => "data-catalog",
                "display_name" => "Data Catalog",
                "description" => NULL,
                "created_at" => "2019-04-05 08:52:26",
                "updated_at" => "2019-04-05 08:52:26",
            ),
            array(
                "id" => 26,
                "parent_id" => 19,
                "name" => "periode",
                "display_name" => "Periode",
                "description" => NULL,
                "created_at" => "2019-04-05 08:52:43",
                "updated_at" => "2019-08-02 07:31:41",
            ),
            array(
                "id" => 27,
                "parent_id" => 0,
                "name" => "master-sap",
                "display_name" => "Master SAP",
                "description" => NULL,
                "created_at" => "2019-04-05 08:52:58",
                "updated_at" => "2019-04-05 08:52:58",
            ),
            array(
                "id" => 28,
                "parent_id" => 27,
                "name" => "sap-asset",
                "display_name" => "SAP Asset",
                "description" => NULL,
                "created_at" => "2019-04-05 08:53:22",
                "updated_at" => "2019-04-05 08:53:22",
            ),
            array(
                "id" => 29,
                "parent_id" => 27,
                "name" => "sap-cost-center",
                "display_name" => "SAP Cost Center",
                "description" => NULL,
                "created_at" => "2019-04-05 08:53:36",
                "updated_at" => "2019-04-05 08:53:36",
            ),
            array(
                "id" => 30,
                "parent_id" => 27,
                "name" => "sap-gl-account",
                "display_name" => "SAP GL Account",
                "description" => NULL,
                "created_at" => "2019-04-05 08:53:57",
                "updated_at" => "2019-04-05 08:53:57",
            ),
            array(
                "id" => 31,
                "parent_id" => 27,
                "name" => "sap-number",
                "display_name" => "SAP Number",
                "description" => NULL,
                "created_at" => "2019-04-05 08:54:23",
                "updated_at" => "2019-04-05 08:54:23",
            ),
            array(
                "id" => 32,
                "parent_id" => 27,
                "name" => "sap-taxes",
                "display_name" => "SAP taxes",
                "description" => NULL,
                "created_at" => "2019-04-05 08:54:41",
                "updated_at" => "2019-04-05 08:54:41",
            ),
            array(
                "id" => 33,
                "parent_id" => 27,
                "name" => "sap-uom",
                "display_name" => "SAP Uom",
                "description" => NULL,
                "created_at" => "2019-04-05 08:54:59",
                "updated_at" => "2019-04-05 08:54:59",
            ),
            array(
                "id" => 34,
                "parent_id" => 27,
                "name" => "sap-vendor",
                "display_name" => "SAP Vendor",
                "description" => NULL,
                "created_at" => "2019-04-05 08:55:16",
                "updated_at" => "2019-04-05 08:55:16",
            ),
            array(
                "id" => 35,
                "parent_id" => 0,
                "name" => "upload-data",
                "display_name" => "Upload Data",
                "description" => NULL,
                "created_at" => "2019-04-05 09:02:59",
                "updated_at" => "2019-04-05 09:02:59",
            ),
            array(
                "id" => 36,
                "parent_id" => 35,
                "name" => "upload-sales-data",
                "display_name" => "upload sales data",
                "description" => NULL,
                "created_at" => "2019-04-05 09:04:35",
                "updated_at" => "2019-08-01 13:57:37",
            ),
            array(
                "id" => 37,
                "parent_id" => 35,
                "name" => "upload-bom-finish-goods",
                "display_name" => "Upload Bom Finish Goods",
                "description" => NULL,
                "created_at" => "2019-04-05 09:04:56",
                "updated_at" => "2019-04-05 09:04:56",
            ),
            array(
                "id" => 38,
                "parent_id" => 35,
                "name" => "upload-bom-semi-finish-goods",
                "display_name" => "upload bom semi finish goods",
                "description" => NULL,
                "created_at" => "2019-04-05 09:05:22",
                "updated_at" => "2019-08-01 14:15:05",
            ),
            array(
                "id" => 39,
                "parent_id" => 35,
                "name" => "upload-master-price-parts",
                "display_name" => "upload master price parts",
                "description" => NULL,
                "created_at" => "2019-04-05 09:05:46",
                "updated_at" => "2019-08-01 14:18:17",
            ),
            array(
                "id" => 40,
                "parent_id" => 35,
                "name" => "budget-upload",
                "display_name" => "Budget_upload",
                "description" => NULL,
                "created_at" => "2019-04-05 09:06:11",
                "updated_at" => "2019-04-26 13:46:19",
            ),
            array(
                "id" => 41,
                "parent_id" => 0,
                "name" => "eps",
                "display_name" => "EPS",
                "description" => NULL,
                "created_at" => "2019-04-05 09:06:34",
                "updated_at" => "2019-04-05 09:06:34",
            ),
            array(
                "id" => 42,
                "parent_id" => 41,
                "name" => "item-category",
                "display_name" => "Item Category",
                "description" => NULL,
                "created_at" => "2019-04-05 09:06:53",
                "updated_at" => "2019-04-05 09:06:53",
            ),
            array(
                "id" => 43,
                "parent_id" => 41,
                "name" => "item",
                "display_name" => "Item",
                "description" => NULL,
                "created_at" => "2019-04-05 09:07:11",
                "updated_at" => "2019-04-05 09:07:11",
            ),
            array(
                "id" => 44,
                "parent_id" => 41,
                "name" => "upload-po",
                "display_name" => "Upload PO",
                "description" => NULL,
                "created_at" => "2019-04-05 09:07:29",
                "updated_at" => "2019-04-05 09:07:29",
            ),
            array(
                "id" => 45,
                "parent_id" => 41,
                "name" => "gr-confirm",
                "display_name" => "GR Confirm",
                "description" => NULL,
                "created_at" => "2019-04-05 09:07:46",
                "updated_at" => "2019-04-25 08:59:35",
            ),
            array(
                "id" => 46,
                "parent_id" => 41,
                "name" => "eps-tracking",
                "display_name" => "EPS Tracking",
                "description" => NULL,
                "created_at" => "2019-04-05 09:08:33",
                "updated_at" => "2019-04-05 09:08:33",
            ),
            array(
                "id" => 47,
                "parent_id" => 0,
                "name" => "unbudget",
                "display_name" => "Unbudget",
                "description" => NULL,
                "created_at" => "2019-04-05 09:08:54",
                "updated_at" => "2019-04-05 09:08:54",
            ),
            array(
                "id" => 48,
                "parent_id" => 47,
                "name" => "list-approval-unbudget",
                "display_name" => "List Approval Unbudget",
                "description" => NULL,
                "created_at" => "2019-04-05 09:09:22",
                "updated_at" => "2019-04-05 09:09:22",
            ),
            array(
                "id" => 49,
                "parent_id" => 47,
                "name" => "create-approval-unbudget",
                "display_name" => "Create Approval Unbudget",
                "description" => NULL,
                "created_at" => "2019-04-05 09:09:52",
                "updated_at" => "2019-04-05 09:09:52",
            ),
            array(
                "id" => 50,
                "parent_id" => 47,
                "name" => "pending-approval-unbudget",
                "display_name" => "Pending Approval Unbudget",
                "description" => NULL,
                "created_at" => "2019-04-05 09:10:20",
                "updated_at" => "2019-04-05 09:10:20",
            ),
            array(
                "id" => 51,
                "parent_id" => 0,
                "name" => "closing",
                "display_name" => "Closing",
                "description" => NULL,
                "created_at" => "2019-04-05 09:11:10",
                "updated_at" => "2019-04-05 09:11:10",
            ),
            array(
                "id" => 52,
                "parent_id" => 51,
                "name" => "closing-capex",
                "display_name" => "Closing Capex",
                "description" => NULL,
                "created_at" => "2019-04-05 09:11:24",
                "updated_at" => "2019-04-05 09:11:24",
            ),
            array(
                "id" => 53,
                "parent_id" => 51,
                "name" => "closing-expense",
                "display_name" => "Closing Expense",
                "description" => NULL,
                "created_at" => "2019-04-05 09:11:40",
                "updated_at" => "2019-04-05 09:11:40",
            ),
            array(
                "id" => 54,
                "parent_id" => 0,
                "name" => "archive",
                "display_name" => "Archive",
                "description" => NULL,
                "created_at" => "2019-04-05 09:12:01",
                "updated_at" => "2019-04-05 09:12:01",
            ),
            array(
                "id" => 55,
                "parent_id" => 54,
                "name" => "archive-capex",
                "display_name" => "Archive Capex",
                "description" => NULL,
                "created_at" => "2019-04-05 09:12:23",
                "updated_at" => "2019-04-05 09:12:23",
            ),
            array(
                "id" => 56,
                "parent_id" => 54,
                "name" => "archive-expense",
                "display_name" => "Archive Expense",
                "description" => NULL,
                "created_at" => "2019-04-05 09:12:42",
                "updated_at" => "2019-08-02 08:16:56",
            ),
            array(
                "id" => 57,
                "parent_id" => 0,
                "name" => "upload",
                "display_name" => "Upload",
                "description" => NULL,
                "created_at" => "2019-04-05 09:13:01",
                "updated_at" => "2019-04-05 09:13:01",
            ),
            array(
                "id" => 58,
                "parent_id" => 57,
                "name" => "upload-capex",
                "display_name" => "Upload Capex",
                "description" => NULL,
                "created_at" => "2019-04-05 09:14:29",
                "updated_at" => "2019-04-05 09:14:29",
            ),
            array(
                "id" => 59,
                "parent_id" => 57,
                "name" => "upload-expense",
                "display_name" => "Upload Expense",
                "description" => NULL,
                "created_at" => "2019-04-05 09:14:57",
                "updated_at" => "2019-04-05 09:14:57",
            ),
            array(
                "id" => 60,
                "parent_id" => 1,
                "name" => "manage-user",
                "display_name" => "Manage User",
                "description" => NULL,
                "created_at" => "2019-04-05 09:16:15",
                "updated_at" => "2019-04-05 09:16:15",
            ),
            array(
                "id" => 61,
                "parent_id" => 7,
                "name" => "pending-asset-assign-no-capex",
                "display_name" => "Pending Asset Assign No Capex",
                "description" => NULL,
                "created_at" => "2019-04-05 09:34:06",
                "updated_at" => "2019-04-05 09:34:06",
            ),
            array(
                "id" => 62,
                "parent_id" => 0,
                "name" => "dashboard",
                "display_name" => "Dashboard",
                "description" => NULL,
                "created_at" => "2019-04-05 10:13:01",
                "updated_at" => "2019-04-05 10:13:01",
            ),
            array(
                "id" => 63,
                "parent_id" => 62,
                "name" => "all-divisions",
                "display_name" => "All Divisions",
                "description" => NULL,
                "created_at" => "2019-04-05 10:26:01",
                "updated_at" => "2019-04-05 10:26:01",
            ),
            array(
                "id" => 64,
                "parent_id" => 62,
                "name" => "adm-divisions",
                "display_name" => "Adm Divisions",
                "description" => NULL,
                "created_at" => "2019-04-05 10:26:23",
                "updated_at" => "2019-04-05 10:26:23",
            ),
            array(
                "id" => 65,
                "parent_id" => 62,
                "name" => "eng-divisions",
                "display_name" => "Eng Divisions",
                "description" => NULL,
                "created_at" => "2019-04-05 10:26:40",
                "updated_at" => "2019-04-05 10:26:40",
            ),
            array(
                "id" => 66,
                "parent_id" => 62,
                "name" => "prd-divisions",
                "display_name" => "Prd Divisions",
                "description" => NULL,
                "created_at" => "2019-04-05 10:26:53",
                "updated_at" => "2019-04-05 10:26:53",
            ),
            array(
                "id" => 67,
                "parent_id" => 19,
                "name" => "approval",
                "display_name" => "Approval",
                "description" => NULL,
                "created_at" => "2019-04-12 14:19:55",
                "updated_at" => "2019-04-12 14:19:55",
            ),
            array(
                "id" => 68,
                "parent_id" => 35,
                "name" => "output-master",
                "display_name" => "output master",
                "description" => NULL,
                "created_at" => "2019-08-01 14:20:40",
                "updated_at" => "2019-08-01 14:20:40",
            ),
            array(
                "id" => 69,
                "parent_id" => 19,
                "name" => "section",
                "display_name" => "Section",
                "description" => NULL,
                "created_at" => "2019-08-02 07:35:27",
                "updated_at" => "2019-08-02 07:35:27",
            ),
            array(
                "id" => 70,
                "parent_id" => 0,
                "name" => "download-sap",
                "display_name" => "Download SAP",
                "description" => NULL,
                "created_at" => "2019-08-02 07:46:37",
                "updated_at" => "2019-08-02 07:46:37",
            ),
            array(
                "id" => 71,
                "parent_id" => 70,
                "name" => "link-to-sap",
                "display_name" => "Link To SAP",
                "description" => NULL,
                "created_at" => "2019-08-02 07:46:55",
                "updated_at" => "2019-08-02 07:46:55",
            ),
        ]);
        
        // Activate FOREIGN_KEY_CHECKS again..
		DB::statement("SET FOREIGN_KEY_CHECKS = 1;");
    }
}
